---
deployment:
  tasks:
    - export DEPLOYPATH=/home/karan11walhe/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp api.php $DEPLOYPATH
    - /bin/cp db_setup.php $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/symbols
    - /bin/chmod 777 $DEPLOYPATH/symbols
